# Generated by Django 3.0.6 on 2020-05-10 22:11

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('Art', 'Art'), ('Educational', 'Educational'), ('Science', 'Science'), ('Games', 'Games'), ('Developmental', 'Developmental')], max_length=43)),
                ('age_range', multiselectfield.db.fields.MultiSelectField(choices=[('Infant', 'Infant'), ('Toddler', 'Toddler'), ('Kindergarten', 'Kindergarten'), ('First-Grade', 'First-Grade'), ('Second-Grade', 'Second-Grade'), ('Third-Grade', 'Third-Grade'), ('Fourth-Grade', 'Fourth-Grade'), ('Fifth-Grade', 'Fifth-Grade'), ('Sixth-Grade', 'Sixth-Grade'), ('Middle-School', 'Middle-School'), ('High-School', 'High-School')], max_length=127)),
                ('summary', models.CharField(max_length=200)),
                ('supplies', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='activity_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.User')),
            ],
        ),
    ]
