# Generated by Django 3.0.6 on 2020-05-11 07:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20200510_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='age_range',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Infant', 'Infant'), ('Toddler', 'Toddler'), ('Kindergarten', 'Kindergarten'), ('First-Grade', 'First-Grade'), ('Second-Grade', 'Second-Grade'), ('Third-Grade', 'Third-Grade'), ('Fourth-Grade', 'Fourth-Grade'), ('Fifth-Grade', 'Fifth-Grade'), ('Sixth-Grade', 'Sixth-Grade')], max_length=101),
        ),
    ]
