# Generated by Django 3.0.6 on 2020-05-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20200511_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
